### ISSUE TITLE
Why do all the requests I send return a 502 error?

### ISSUE THREAD

**Issue by bupt01** [codingsoo/ARAT-RL#2]
Hello, I have deployed both the program to be tested and ARAT-RL in the same container, but I am curious why all the requests I send return a 502 error?If you can help me, I would be very grateful.

**Comment by codingsoo** [comment]
Hi, can you attach your proxy log? It seems like there's an error in the proxy server.

**Comment by codingsoo** [comment]
I am closing this since I did not get any reply. Please reopen this if you still have the issue!
